name: Plugin action
on:
  push:
    branches: ['main', 'master']
  pull_request:
    types: [opened, edited, reopened]
  release:
    types: [published]

jobs:
  plugin-action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: CI
        uses: matmair/inventree-meta-plugin/.github/workflows/plugin_action.yaml@next
        with:
          python_version: 3.13
